/*
 *  Created by Medvediev Viktor [mvproject]
 *  Copyright © 2023
 *  last modified : 04.05.23, 10:59
 *
 */

package com.mvproject.tinyiptv.ui.theme

import androidx.compose.ui.graphics.Color

val videoAppLightPrimary = Color(0xFF315DA8)
val videoAppLightOnPrimary = Color(0xFFFFFFFF)
val videoAppLightPrimaryContainer = Color(0xFFD8E2FF)
val videoAppLightOnPrimaryContainer = Color(0xFF001A41)
val videoAppLightSecondary = Color(0xFF4F56A9)
val videoAppLightOnSecondary = Color(0xFFFFFFFF)
val videoAppLightSecondaryContainer = Color(0xFFE0E0FF)
val videoAppLightOnSecondaryContainer = Color(0xFF030865)
val videoAppLightTertiary = Color(0xFF9B432C)
val videoAppLightOnTertiary = Color(0xFFFFFFFF)
val videoAppLightTertiaryContainer = Color(0xFFFFDBD2)
val videoAppLightOnTertiaryContainer = Color(0xFF3C0800)
val videoAppLightError = Color(0xFFBA1A1A)
val videoAppLightErrorContainer = Color(0xFFFFDAD6)
val videoAppLightOnError = Color(0xFFFFFFFF)
val videoAppLightOnErrorContainer = Color(0xFF410002)
val videoAppLightBackground = Color(0xFFFEFBFF)
val videoAppLightOnBackground = Color(0xFF1B1B1F)
val videoAppLightSurface = Color(0xFFFEFBFF)
val videoAppLightOnSurface = Color(0xFF1B1B1F)
val videoAppLightSurfaceVariant = Color(0xFFE1E2EC)
val videoAppLightOnSurfaceVariant = Color(0xFF44474F)
val videoAppLightOutline = Color(0xFF75777F)
val videoAppLightInverseOnSurface = Color(0xFFF2F0F4)
val videoAppLightInverseSurface = Color(0xFF303033)
val videoAppLightPrimaryInverse = Color(0xFFADC6FF)
val videoAppLightSurfaceTint = Color(0xFFFFDBD2)
val videoAppLightOutlineVariant = Color(0xFF151518)
val videoAppLightScrim = Color(0xFF000000)

val videoAppDarkPrimary = Color(0xFFADC6FF)
val videoAppDarkOnPrimary = Color(0xFF002E69)
val videoAppDarkPrimaryContainer = Color(0xFF0F448E)
val videoAppDarkOnPrimaryContainer = Color(0xFFD8E2FF)
val videoAppDarkSecondary = Color(0xFFBEC2FF)
val videoAppDarkOnSecondary = Color(0xFF1E2578)
val videoAppDarkSecondaryContainer = Color(0xFF363E90)
val videoAppDarkOnSecondaryContainer = Color(0xFFE0E0FF)
val videoAppDarkTertiary = Color(0xFFFFB4A1)
val videoAppDarkOnTertiary = Color(0xFF5E1704)
val videoAppDarkTertiaryContainer = Color(0xFF7D2D18)
val videoAppDarkOnTertiaryContainer = Color(0xFFFFDBD2)
val videoAppDarkError = Color(0xFFFFB4AB)
val videoAppDarkErrorContainer = Color(0xFF93000A)
val videoAppDarkOnError = Color(0xFF690005)
val videoAppDarkOnErrorContainer = Color(0xFFFFDAD6)
val videoAppDarkBackground = Color(0xFF1B1B1F)
val videoAppDarkOnBackground = Color(0xFFE3E2E6)
val videoAppDarkSurface = Color(0xFF1B1B1F)
val videoAppDarkOnSurface = Color(0xFFE3E2E6)
val videoAppDarkSurfaceVariant = Color(0xFF44474F)
val videoAppDarkOnSurfaceVariant = Color(0xFFC4C6D0)
val videoAppDarkOutline = Color(0xFF8E9099)
val videoAppDarkInverseOnSurface = Color(0xFF1B1B1F)
val videoAppDarkInverseSurface = Color(0xFFE3E2E6)
val videoAppDarkPrimaryInverse = Color(0xFF315DA8)
val videoAppDarkSurfaceTint = Color(0xFFFFDBD2)
val videoAppDarkOutlineVariant = Color(0xFF151518)
val videoAppDarkScrim = Color(0xFF000000)